# Setup
title: Hola! this is Joy
description: ʕ •ᴥ•ʔ
url: https://vszhub.github.io
avatar: /IMG_4405.JPG
paginate: 5
permalink: pretty
cover_image: /23.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username:
  card: summary
logo: logo.png
social:
  name: Joy Luo
  links:
    - https://twitter.com/
    - https://github.com/joy3luo
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: G-TG0XJZG53F

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Joy Luo
  url: https://github.com/joy3luo/
  email: zshyly@gmail.com
